version: '3.7'

volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:

services:
  pihole:
    container_name: pihole
    image: ghcr.io/zigapovhe/docker-pihole-unbound:master
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    environment:
      FTLCONF_REPLY_ADDR4: ${SERVER_IP}
      TZ: ${TZ}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      WEBUIBOXEDLAYOUT: ${WEBUIBOXEDLAYOUT}
      WEBTHEME: ${WEBTHEME}
      TEMPERATUREUNIT: c
      WEBPASSWORD: ${WEBPASSWORD}
      REV_SERVER: ${REV_SERVER}
      REV_SERVER_TARGET: ${REV_SERVER_TARGET}
      REV_SERVER_DOMAIN: ${REV_SERVER_DOMAIN}
      REV_SERVER_CIDR: ${REV_SERVER_CIDR}
      DHCP_ACTIVE: ${DHCP_ACTIVE} #DHCP Server
      DHCP_START: ${DHCP_START}
      DHCP_END: ${DHCP_END}
      DHCP_ROUTER: ${DHCP_ROUTER}
      DHCP_LEASETIME: ${DHCP_LEASETIME}
      DHCP_IPv6: ${DHCP_IPV6}
      PIHOLE_DNS_: 127.0.0.1#5335 # Hardcoded to our Unbound server
      DNSSEC: "true" # Enable DNSSEC
      DNS_BOGUS_PRIV: "true" #Never forward reverse lookups for private ranges
      DNS_FQDN_REQUIRED: "true" #Never forward non-FQDNs
      
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
      - '${UNBOUND_CONFIG_MOUNT}'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN  
      - NET_RAW
      - SYS_NICE
    network_mode: "host"
    restart: unless-stopped

